sudo: required
services: 
    - docker

before_install:
    - docker build -t kevjett/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true kevjett/docker-react npm run test

deploy:
    provider: azure_web_apps
    on: master
    username: AZURE_WA_USERNAME
    password: AZURE_WA_PASSWORD
    site: AZURE_WA_SITE