# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pr:
  - master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'kevjett/docker-react'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: 'docker build -t $(imageName) -f Dockerfile.dev .'
      displayName: Build image

    - script: 'docker run -e CI=true $(imageName) npm run test'
      displayName: Run tests